name: 'GitHub Contribution Calendar Theme Detector'
description: 'Detects the current GitHub contribution calendar theme and extracts color palettes for both light and dark modes'
author: 'diverger'

branding:
  icon: 'calendar'
  color: 'green'

inputs:
  github-username:
    description: 'GitHub username to check for contribution calendar theme'
    required: false
    default: ${{ github.repository_owner }}

outputs:
  holiday_detected:
    description: 'Whether a holiday theme is currently active (true/false)'
  theme_name:
    description: 'Name of the detected theme (e.g., halloween, christmas, default)'
  light_color_palette:
    description: 'Comma-separated list of colors for light theme'
  dark_color_palette:
    description: 'Comma-separated list of colors for dark theme'
  light_grid_colors:
    description: 'JSON array of light theme grid colors with levels'
  dark_grid_colors:
    description: 'JSON array of dark theme grid colors with levels'

runs:
  using: 'docker'
  # Image will be updated to use SHA digest during release process
  # Format: docker://ghcr.io/OWNER/REPO@sha256:xxxxx
  image: 'docker://ghcr.io/diverger/gh-contribution-calendar-theme@sha256:2e059eed2731b3c72e95227884d23a0526b2c370d67798d3a5835ce818696148'
  env:
    GITHUB_USERNAME: ${{ inputs.github-username }}
